// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBz5fScHnJsSPBK6_RMiZSqOdzTdN78-S4',
    appId: '1:989115786524:web:695f78b3d47358689386d9',
    messagingSenderId: '989115786524',
    projectId: 'mylez-loveefy-app',
    authDomain: 'mylez-loveefy-app.firebaseapp.com',
    storageBucket: 'mylez-loveefy-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDinvztlTu9YCRJ-Ne4GxfDFaapFHoAgpQ',
    appId: '1:989115786524:android:8c08052fab5e0f019386d9',
    messagingSenderId: '989115786524',
    projectId: 'mylez-loveefy-app',
    storageBucket: 'mylez-loveefy-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCM3RvCJpg8onclOX_fFUiWmE6GKlFKmTA',
    appId: '1:989115786524:ios:06982c678cf123649386d9',
    messagingSenderId: '989115786524',
    projectId: 'mylez-loveefy-app',
    storageBucket: 'mylez-loveefy-app.appspot.com',
    iosClientId: '989115786524-tim8l22t739vffksj4gea66ftq932eub.apps.googleusercontent.com',
    iosBundleId: 'com.example.loveefy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCM3RvCJpg8onclOX_fFUiWmE6GKlFKmTA',
    appId: '1:989115786524:ios:06982c678cf123649386d9',
    messagingSenderId: '989115786524',
    projectId: 'mylez-loveefy-app',
    storageBucket: 'mylez-loveefy-app.appspot.com',
    iosClientId: '989115786524-tim8l22t739vffksj4gea66ftq932eub.apps.googleusercontent.com',
    iosBundleId: 'com.example.loveefy',
  );
}
